version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run: npm run test
  test:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run: npm run test
  pest:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run: npm run test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
      - pest
  tom_and_pistazie:
    jobs:
      - build
      - test
      - pest
  pasta_and_tomatoes:
    jobs:
      - build
      - test
      - pest
  gin_and_tonic:
    jobs:
      - build
      - test
      - pest
  santa_and_christmas:
    jobs:
      - build
      - test
      - pest
  eric_and_benz:
    jobs:
      - build
      - test
      - pest
  peace_and_love:
    jobs:
      - build
      - test
      - pest
